(cl:in-package tada_ros-msg)
(cl:export '(MODE-VAL
          MODE
          DURATION-VAL
          DURATION
          MOTOR1_MOVE-VAL
          MOTOR1_MOVE
          MOTOR2_MOVE-VAL
          MOTOR2_MOVE
          MOTOR1_TORQUE-VAL
          MOTOR1_TORQUE
          MOTOR2_TORQUE-VAL
          MOTOR2_TORQUE
          PF_CMD-VAL
          PF_CMD
          EV_CMD-VAL
          EV_CMD
          PF_CURR-VAL
          PF_CURR
          EV_CURR-VAL
          EV_CURR
          CPU0-VAL
          CPU0
          CPU1-VAL
          CPU1
          CPU2-VAL
          CPU2
          CPU3-VAL
          CPU3
          T-VAL
          T
          VALID-VAL
          VALID
))