(cl:defpackage tada_ros-msg
  (:use )
  (:export
   "<CONFIGMSG>"
   "CONFIGMSG"
   "<EUROPAMSG>"
   "EUROPAMSG"
   "<IMUDATAMSG>"
   "IMUDATAMSG"
   "<KILLCONFIRMATIONMSG>"
   "KILLCONFIRMATIONMSG"
   "<MOTORDATAMSG>"
   "MOTORDATAMSG"
   "<MOTORLISTENMSG>"
   "MOTORLISTENMSG"
   "<RECONDATAMSG>"
   "RECONDATAMSG"
   "<USERCHOICEMSG>"
   "USERCHOICEMSG"
  ))

