# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tada_ros/ConfigMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ConfigMsg(genpy.Message):
  _md5sum = "9fbfd22fef180f2f17264d3d24989496"
  _type = "tada_ros/ConfigMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 x_loc
float64 y_loc
float64 z_loc
float64 angle_1
float64 angle_2
float64 angle_3
"""
  __slots__ = ['x_loc','y_loc','z_loc','angle_1','angle_2','angle_3']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_loc,y_loc,z_loc,angle_1,angle_2,angle_3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConfigMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x_loc is None:
        self.x_loc = 0.
      if self.y_loc is None:
        self.y_loc = 0.
      if self.z_loc is None:
        self.z_loc = 0.
      if self.angle_1 is None:
        self.angle_1 = 0.
      if self.angle_2 is None:
        self.angle_2 = 0.
      if self.angle_3 is None:
        self.angle_3 = 0.
    else:
      self.x_loc = 0.
      self.y_loc = 0.
      self.z_loc = 0.
      self.angle_1 = 0.
      self.angle_2 = 0.
      self.angle_3 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.x_loc, _x.y_loc, _x.z_loc, _x.angle_1, _x.angle_2, _x.angle_3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x_loc, _x.y_loc, _x.z_loc, _x.angle_1, _x.angle_2, _x.angle_3,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.x_loc, _x.y_loc, _x.z_loc, _x.angle_1, _x.angle_2, _x.angle_3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x_loc, _x.y_loc, _x.z_loc, _x.angle_1, _x.angle_2, _x.angle_3,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
