# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tada_ros/MotorListenMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MotorListenMsg(genpy.Message):
  _md5sum = "458821757342d0f4a30215b0ee1690f8"
  _type = "tada_ros/MotorListenMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 curr_pos1
int32 curr_pos2
int64 toff
float32 t"""
  __slots__ = ['curr_pos1','curr_pos2','toff','t']
  _slot_types = ['int32','int32','int64','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       curr_pos1,curr_pos2,toff,t

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorListenMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.curr_pos1 is None:
        self.curr_pos1 = 0
      if self.curr_pos2 is None:
        self.curr_pos2 = 0
      if self.toff is None:
        self.toff = 0
      if self.t is None:
        self.t = 0.
    else:
      self.curr_pos1 = 0
      self.curr_pos2 = 0
      self.toff = 0
      self.t = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2iqf().pack(_x.curr_pos1, _x.curr_pos2, _x.toff, _x.t))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.curr_pos1, _x.curr_pos2, _x.toff, _x.t,) = _get_struct_2iqf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2iqf().pack(_x.curr_pos1, _x.curr_pos2, _x.toff, _x.t))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.curr_pos1, _x.curr_pos2, _x.toff, _x.t,) = _get_struct_2iqf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2iqf = None
def _get_struct_2iqf():
    global _struct_2iqf
    if _struct_2iqf is None:
        _struct_2iqf = struct.Struct("<2iqf")
    return _struct_2iqf
